### ISSUE TITLE
Database connection issues

### ISSUE THREAD

**Issue by dsite** [codemonauts/docker-craft-cms-dev-env#4]
I'm trying to get Craft CMS working in a Docker environment. I came across this project, and it looks promising. 

I'm able to get the `craft start` to spin up. And I've used `craft create` to create a database based on what's in my .env file. But when I go to http://localhost:8080/admin to install Craft, I get the following error:
```
PDO exception: SQLSTATE[HY000] [1045] 
Access denied for user 'dbusername'@'172.17.0.4' 
(using password: YES)
```

I read the [previous database connection issue](https://github.com/codemonauts/docker-craft-cms-dev-env/issues/3), and I've made sure that my database server is named `mysql`, not `localhost`. 

I'd love any suggestions you might have for how I might be able to proceed. Thank you for your time.

**Comment by dsite** [comment]
Never mind. I dug around a little more and switched the username/password to root/root and it worked.

Have a nice day!

**Comment by fleaz** [comment]
This should be present in the documentation. I added it in 2edc44c468d2266e0453068f4831719dede54cc8 to the README

Thanks for mentioning it and good thing you figured it out nonetheless :)

**Comment by dsite** [comment]
Thanks! That's definitely clearer. 

And thanks for the tool. I've tried a few other approaches and this seems nice and simple.
