### ISSUE TITLE
mysql no longer being created

### ISSUE THREAD

**Issue by dsite** [codemonauts/docker-craft-cms-dev-env#6]
Hi there,

I'm not sure what has happened, but I can no longer connect to the mysql container when I do a `craft start` command. It looks like it starts, but it doesn't:

```
$ craft start
> Pulling new craft container
> Need to start Mysql
> Started MySQL container
> Need to start redis
> Started Redis container
> Need to start craft
> Started Craft CMS environment in /site/path
> Now create something awesome 🚀
```

But when I try to do a `craft shell` or a `craft create [database]` I get:

```
Error response from daemon: Cannot link to a non running container: /mysql AS /craft/mysql
```

When I check with `docker ps -a`, I see:

```
$ docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                  NAMES
a3325e28b434        codemonauts/craft-cms-dev-env   "run.sh"                 3 seconds ago       Up 2 seconds        0.0.0.0:8080->80/tcp   craft
c9ad4dd7f4e9        redis:5.0                       "docker-entrypoint.s…"   4 seconds ago       Up 3 seconds        6379/tcp               redis
```

I have done a `craft selfupdate` command. I have downloaded the latest version manually and replaced `~/bin/craft` with your default `craft` file. And I can't seem to get it working again.

I've tried to remove any other docker containers/networks/etc. to make sure that nothing was interfering with it. I've restarted docker. I've restarted my computer. Nothing seems to get it running again.

It was working so well, but now I'm a little stuck. Any troubleshooting suggestions?

**Comment by fleaz** [comment]
Hey @dsite,

my assumption is that the script starts the mysql container but immediately stops it because MySQL fails to start. Can you move the database directory (`~/databases`) somewhere else (e.g. `~/databases_old`) and do craft stopall/start again? If it's working then, some of your database files are corrupted which caused mysql to crash and stopped the container.

**Comment by dsite** [comment]
Thanks so much for your quick response. I think I finally have everything more or less back up and running with a new database.

As long as I have you here... is there a way to configure this to run MySQL 5.7? I thought that updating the `craft` script to `MYSQL_CONTAINER="mysql:5.7"` and restarting might do it, but that seems to break things. (And, now that I think about it, that might have been the cause my initial issue.)

Thanks again for your help, and for such a nifty tool. Have a wonderful weekend!

**Comment by fleaz** [comment]
Thanks for the kind words :) Nice to hear that you like our tool.

Between 5.6 and 5.7 were a few changes which probably caused the container to crash during start and probably also corrupted your databases dir.

When you want to use 5.7 you have to stop all container, delete the ~/databases directory, change the `craft` script like you did earlier and then run start again. This way mysql 5.7 will directly create a new database dir and everything should continue to work when you create and import new DBs

Best regards,
Felix
